### ISSUE TITLE
bonds market order cancel

### ISSUE THREAD

**Issue by jjhesk** [ixofoundation/ixo-blockchain#160]
is there a way to cancel the market order or any buy sell orders under some conditions?

referencing from the below module:

```

Usage:
  dpcli tx bonds buy [bond-token-with-amount] [max-prices] [bond-did] [buyer-did] [flags]

Examples:
buy 10abc 1000res1 U7GK8p8rVhJMKhBVRCJJ8c <buyer-sovrin-did>
buy 10abc 1000res1,1000res2 U7GK8p8rVhJMKhBVRCJJ8c <buyer-sovrin-did>

Flags:
  -a, --account-number uint      The account number of the signing account (offline mode only)
  -b, --broadcast-mode string    Transaction broadcasting mode (sync|async|block) (default "sync")
      --dry-run                  ignore the --gas flag and perform a simulation of a transaction, but don't broadcast it
      --fees string              Fees to pay along with transaction; eg: 10uatom
      --from string              Name or address of private key with which to sign
      --gas string               gas limit to set per-transaction; set to "auto" to calculate required gas automatically (default 200000) (default "200000")
      --gas-adjustment float     adjustment factor to be multiplied against the estimate returned by the tx simulation; if the gas limit is set manually this flag is ignored  (default 1)
      --gas-prices string        Gas prices to determine the transaction fee (e.g. 10uatom)
      --generate-only            Build an unsigned transaction and write it to STDOUT (when enabled, the local Keybase is not accessible and the node operates offline)
  -h, --help                     help for buy
      --indent                   Add indent to JSON response
      --keyring-backend string   Select keyring's backend (os|file|test) (default "os")
      --ledger                   Use a connected Ledger device
      --memo string              Memo to send along with transaction
      --node string              <host>:<port> to tendermint rpc interface for this chain (default "tcp://localhost:26657")
  -s, --sequence uint            The sequence number of the signing account (offline mode only)
      --trust-node               Trust connected full node (don't verify proofs for responses) (default true)
  -y, --yes                      Skip tx broadcasting prompt confirmation

Global Flags:
      --chain-id string   Chain ID of tendermint node
  -e, --encoding string   Binary encoding (hex|b64|btc) (default "hex")
      --home string       directory for config and data (default "/Users/hesk/.dpcli")
  -o, --output string     Output format (text|json) (default "text")
      --trace             print out full stack trace on errors
```

**Comment by migueldingli1997** [comment]
Currently, this is not possible. For this to become possible, the orders will at least require an ID. However, even if this is added, there are other complications involved with cancelling orders.

With the batched order processing that we've implemented for front-running prevention, the batch-cumulative buy price and sell price (seen when querying a batch) are re-calculated with every new order. A new buy order typically causes the cumulative buy price to increase (assuming an upward curve). Any existing buy order which cannot pay at the new buy price gets automatically cancelled.

If we allow cancelling of orders, there can be scenarios where users intentionally add and immediately cancel huge orders, which can cause other users' buy orders to get cancelled, since they will not be able to pay at the increased buy price (even if it was just increased temporarily). A follow-up to this can be that the user adds a new order at a cheaper price, given that there will now be less buy orders in the batch, which means a lower buy price. Even if the user does not add a new order, the effect of causing buy orders to get cancelled drives up the sell price for sell orders.

**Comment by jjhesk** [comment]
The bid ask pricing are driven by the market behavior and it is the rule of the game. If there is no such features for cancelling orders then it will not able to mimic the traditional exchange the market behaviour. I recommend to have this feature that can be turned on and off by the bond maker.

**Comment by migueldingli1997** [comment]
Thanks for your recommendation. I recognise that this is an important feature to have in a traditional exchange. However, the primary intention of the orders model that we have implemented is targeted more towards front-running prevention and averaged-out buy and sell prices. Implementing a full-fledged exchange is not the intention at this point.

**Comment by jjhesk** [comment]
There is a complete solution with this logic.

Quantity: 
number of tokens users want to buy or sell. That must be rounded by lot size. Internally it can be multiplied by 1e8(10^8) in order to store as an integer in the range of int64.

Time: 
entry time of the order, which is the block number(height) the order gets booked in.

TimeInForce:
GTE: Good Till Expire. Order would stay effective until expire time. Order may expire in the UTC midnight after more than 259, 200 blocks, which is 72 hours in term of blocking time.
IOC: Immediate or Cancel. Orders would be executed as much as it can in the booking block round and then got canceled back if there is still quantity left.

**Comment by migueldingli1997** [comment]
Thank you for this information. We or anyone using the bonds module will definitely take it into consideration when thinking about implementing a DEX.
