### ISSUE TITLE
Fee approximation question

### ISSUE THREAD

**Issue by gwn** [ixofoundation/ixo-blockchain#221]
Hey,

I'm trying to understand the fee approximation algorithm here:

https://github.com/ixofoundation/ixo-blockchain/blob/master/x/ixo/internal/types/auth.go#L99-L121

I need this ported to Javascript and the client side. I'm not asking for code :), but some details regarding the steps would be helpful for me for porting, especially since I'm no blockchain expert.

Also please inform me if this is not the right place to ask such a question.

**Comment by migueldingli1997** [comment]
Hi,

The key function there is the `EnrichWithGas` function, which is a standard Cosmos SDK function. You can read a (very) short description about it here:
https://pkg.go.dev/github.com/PashaKlybik/cosmos-sdk@v0.34.7/client/utils#EnrichWithGas

Basically what it does is that it simulates the processing of the transaction to figure out how expensive it will be (i.e. how much gas it will consume). I do not recommend that you implement this on the client side since there's a lot happening in the background and you are better off requesting the gas consumption from the blockchain. This is available via the POST endpoints for each module: https://cosmos.network/rpc/v0.38.3

For ixo transactions, similar endpoints are available but are not documented! There is also a `/txs/sign_data` endpoint that one can use but even though it is convenient, I suggest avoiding it if possible.

After `EnrichWithGas` is used, the function just uses the `txBldr` (now containing gas consumption information from `EnrichWithGas`) to calculate the actual fee (in IXO tokens) using the formula `fee = gas * gas prices` where gas prices is approximated using an expected value of `0.025uixo`.

For example if:
- Transaction will consume `100,000` gas (note: no currencies here)
- Validator will (approximately) charge `0.025uixo` for each unit of gas
- Total fee will be `100,000 x 0.025uixo = 2500uixo`

**Comment by gwn** [comment]
Thank you @migueldingli1997 , your detailed response is really appreciated! I'm closing the issue, will follow up if necessary.
